name: k6 local test run on Windows

on: 
  push:
    branches-ignore:
      - "**" # this effectively disables this workflow - never runs

jobs:
  k6_local_test:
    name: k6 local test run on windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: download and extract k6 release binaries
        run: |
          curl -L https://github.com/grafana/k6/releases/download/v0.46.0/k6-v0.46.0-windows-amd64.zip -o k6.zip
          7z.exe e k6.zip
        shell: bash

      - name: k6 test
        run: ./k6.exe run ./tests/threshold.js
        shell: bash