version: "3"
networks:
  workshop-k6-nerdearla2023_default:
services:
  quickpizza:
    image: ghcr.io/grafana/quickpizza-local:latest
    ports:
      - 3333:3333

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards  panelTitleSearch   traceToMetrics pyroscopeFlameGraph scenes lokiQuerySplitting timeSeriesTable dashboardEmbed exploreScrollableLogsContainer lokiFormatQuery recordedQueriesMulti logsExploreTableVisualisation featureToggleAdminPage canvasPanelNesting
      - GF_INSTALL_PLUGINS=grafana-polystat-panel,yesoreyeram-infinity-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/
