pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo gpg -k
    sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
    echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
    sudo apt-get update
    sudo apt-get install k6
  displayName: Install k6 tool

- script: |
    k6 version
  displayName: Check if k6 is installed

- script: |
    k6 run tests/local.js
  displayName: Run k6 load test within Azure Pipelines

- script: |
    k6 login cloud --token $(k6cloud.token)
    k6 cloud --quiet tests/cloud.js
  displayName: Run k6 cloud load test within Azure Pipelines