pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      docker run -i -v `pwd`:/src grafana/k6 run /src/tests/local.js
    displayName: Run k6 from Docker locally

  - script: |
      docker run -i -v `pwd`:/src -e K6_CLOUD_TOKEN=$(k6cloud.token) grafana/k6 cloud /src/tests/local.js
    displayName: Run k6 from Docker offloading to cloud
