name: Testing QuickPizza
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:0.3.0
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: script.js
          flags: -o experimental-prometheus-rw 

        env:
          BASE_URL: "http://quickpizza:3333"
          THRESHOLD:  ${{ env.THRESHOLD }}
          K6_PROMETHEUS_RW_USERNAME:  ${{ secrets.K6_PROMETHEUS_RW_USERNAME }}
          K6_PROMETHEUS_RW_PASSWORD: ${{ secrets.K6_PROMETHEUS_RW_PASSWORD }}
          K6_PROMETHEUS_RW_SERVER_URL: ${{ secrets.PROMETHEUS_RW_SERVER_URL }}

          - name: Publish Test Report
          uses: mikepenz/action-junit-report@v4
          if: success() || failure() # always run even if the previous step fails
          with:
            report_paths: 'junit.xml'