name: Testing QuickPizza
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:0.3.0
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: script.js
        env:
          BASE_URL: "http://quickpizza:3333"
          THRESHOLD: env.THRESHOLD