name: Testing QuickPizza
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      quickpizza:
        image: ghcr.io/grafana/quickpizza-local:0.3.0
        ports:
          - 3333:3333

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run local k6 test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: script.js
          flags: -o experimental-prometheus-rw --tag testid=nerdearla2023-quickpizza-${{ github.run_number }}

        env:
          BASE_URL: "http://quickpizza:3333"
          THRESHOLD:  ${{ vars.THRESHOLD }}
          K6_PROMETHEUS_RW_USERNAME:  ${{ secrets.K6_PROMETHEUS_RW_USERNAME }}
          K6_PROMETHEUS_RW_PASSWORD: ${{ secrets.K6_PROMETHEUS_RW_PASSWORD }}
          K6_PROMETHEUS_RW_SERVER_URL: ${{ vars.K6_PROMETHEUS_RW_SERVER_URL }}
          K6_PROMETHEUS_RW_STALE_MARKERS: true
          K6_PROMETHEUS_RW_TREND_STATS: "p(95),p(99),min,max"

      - name: Store performance test results
        uses: actions/upload-artifact@v3
        with:
            name: k6-summary-report
            path: summary.json

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
            report_paths: 'junit.xml'